databases:
  - name: zol0-postgres
    region: singapore
    plan: free
    postgresMajorVersion: "15"

services:
  - name: zol0-backend-api
    type: web
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: Dockerfile.api
    envVars:
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        fromDatabase:
          name: zol0-postgres
          property: connectionString

  - name: zol0-bot-worker
    type: worker
    runtime: docker
    plan: starter
    region: singapore
    dockerfilePath: Dockerfile.worker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zol0-postgres
          property: connectionString

  - name: zol0-dashboard
    type: web
    runtime: static
    buildCommand: cd dashboard && npm install && npm run build
    staticPublishPath: dashboard/dist
    envVars:
      - key: VITE_API_URL
        value: https://zol0-backend.onrender.com
